import json, os

def chaveOrd(emd):
    return emd['dataEMD']

# Abrir o json
ficheiro = open('emd.json')
bd = json.load(ficheiro)
ficheiro.close

# Ordenar o conteudo por data
bd.sort(reverse=True, key = chaveOrd)

# Criar pagina html para cada pessoa
for e in bd:
    f = open('./emdSite/emd'+e['index']+'.html','w')

preHTML = f""""
<!DOCTYPE html>
<html>
    <head>
        <title>Exame Médico Desportivo: Emily Terrell</title>
        <link rel="stylesheet" href="w3.css">
        <meta charset="UTF-8">
    </head>

    <body>
        <div class="w3-card-4">

            <header class="w3-container w3-purple">
              <h3>Exame Médico Desportivo: Emily Terrell</h3>
            </header>
            
            <div class="w3-container">
                <table class="w3-ul w3-card-4" style="width:50%">
"""

posHTML = f"""
                </ul>
            </div>

            <footer class="w3-container w3-purple">
                <h5>Generated by EMApp::EngWeb2024::a100837</h5>
                <address>
                    <a href="index.html"> Voltar á página principal </a>
                </address>
            </footer>

            </div>
    </body>
</html>
"""

conteudo = ""

for e in bd:
    conteudo += f"""
                <li>
                    <a href="emd{e['index']}.html">
                        {e['dataEMD']}: {e['nome']['primeiro']} {e['nome']['último']} </a>
                </li>
"""

f.write(pagHTML)
f.close